name: CI

on: [push]

jobs:
  build:
    env: 
      DOCKER_HUB_REPOSITORY: forumsitecore
      DOCKER_HUB_ORGANIZATION: kglassmire
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: aarnott/nbgv@master
    - name: install tree
      run: apt install -y tree
    - name: print environment variables
      run: printenv
    - name: docker build
      run: docker build . -t $DOCKER_HUB_ORGANIZATION/$DOCKER_HUB_REPOSITORY
    - name: output directory structure of tree
      run: tree $GITHUB_WORKSPACE
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
