name: CI

on: [push]

jobs:
  env: 
    DOCKER_HUB_REPOSITORY: forumsitecore
    DOCKER_HUB_ORGANIZATION: kglassmire

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: aarnott/nbgv@master
    - name: print environment variables
      run: printenv
    - name: docker build
      run: docker build . -t $DOCKER_HUB_ORGANIZATION/$DOCKER_HUB_REPOSITORY
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
