name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: aarnott/nbgv@master
    - name: docker build
      run: docker build . -t forumsitecore
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
